EEGLAB_RAW_SET:
  montage: "EEGLAB"
  description: "EEGLAB SET File (Continuous)"

EEGLAB_EPOCHS_SET:
  montage: "EEGLAB"
  description: "EEGLAB SET File (Epoched)"

EGI_128_RAW:
  montage: "GSN-HydroCel-128"
  description: "EGI 128-channel Raw"

EGI_128_MFF:
  montage: "GSN-HydroCel-128"
  description: "EGI 128-channel MFF"

MNE_FIF:
  montage: "MNE"
  description: "MNE FIF"

NEURONEXUS_30_EDF:
    montage: "Custom"
    description: "Neuronexus 30-channel Multielectrode Array"