# docker build --platform linux/amd64 -t ghcr.io/cincibrainlab/signalfloweeg-jdatascience:latest .
ARG REGISTRY=quay.io
ARG OWNER=jupyter
ARG BASE_CONTAINER=$REGISTRY/$OWNER/datascience-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Ernie Pedapati <ernest.pedapati@cchmc.org>"

USER root

# Install additional packages
RUN apt-get update && apt-get install -y nala && \
    nala install -y libx11-dev wget ca-certificates curl git nano unzip zip software-properties-common build-essential && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \ 
    apt-get install -y git-lfs

USER ${NB_UID}

# Install conda packages
RUN mamba install --name=base nb_conda_kernels -y
RUN mamba create -c conda-forge -n signalflowenv python=3.11 mne-base ipykernel mne-bids mne-features \
    mne-connectivity mne-icalabel pyvista pyvistaqt vtk qtpy ipympl pyqtgraph \
    numba nibabel nilearn cupy pandas threadpoolctl \
    ipywidgets trame pip -y && mamba init 

#Install Quarto
WORKDIR /tmp
USER root
RUN ARCH=$(uname -m) && \
    case $ARCH in \
        x86_64) \
            QUARTO_ARCH=linux-amd64 ;; \
        aarch64) \
            QUARTO_ARCH=linux-arm64 ;; \
        *) \
            echo "Unsupported architecture: $ARCH" && exit 1 ;; \
    esac && \
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.551/quarto-1.4.551-$QUARTO_ARCH.tar.gz && \
    tar -C /opt -xvzf quarto-1.4.551-$QUARTO_ARCH.tar.gz && \
    ln -s /opt/quarto-1.4.551/bin/quarto /usr/bin/quarto && \
    rm quarto-1.4.551-$QUARTO_ARCH.tar.gz
    #quarto install tinytex && \
    #quarto install chromium
    #quarto check && \

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    apt-transport-https \
    && rm -rf /var/lib/apt/lists/* \
    && wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg \
    && install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg \
    && rm -f packages.microsoft.gpg \
    && echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list \
    && apt-get update \
    && apt-get install -y code 

USER ${NB_UID}
RUN echo "alias code='code --no-sandbox'" >> ~/.bashrc
RUN /opt/conda/envs/signalflowenv/bin/pip install -e git+https://github.com/cincibrainlab/signalfloweeg_py.git#egg=signalfloweeg --src /home/jovyan/src/signalfloweeg_dev && \
    /opt/conda/envs/signalflowenv/bin/pip install fooof fuzzywuzzy python-Levenshtein meegkit bycycle pyyaml humanize

WORKDIR /home/jovyan

# Configure container startup
# Default password: welcome (see https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html)
CMD ["start-notebook.py", "--ServerApp.root_dir=/work", "--PasswordIdentityProvider.hashed_password='argon2:$argon2id$v=19$m=10240,t=10,p=8$vmE0qko04/eNJxcO9NjRkw$i9JRa6BICOuwPySh1EQjjp8SeAUph90UH0dw6A6Kz+Q'"]
