project:
  type: book

book:
  title: "SignalFlowEeg Python Documentation"
  author: "Pedapati Lab"
  date: "3/11/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Input/Output"
      chapters: 
        - io_load_eeg.qmd
        - io_load_eeg2_customize.qmd
    - part: "Utilities"
      chapters: 
        - utils_load_catalog.qmd
    - part: "Visualization"
      chapters: 
        - viz_interactive_plots.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: zephyr
    fontsize: 1.1em
    linestretch: 1.7
  pdf:
    documentclass: scrreprt



