# Configuration settings
database:
  url: postgresql://sfportal:sfportal@localhost:3002/sfportal
  initialize: False

# This file is used to configure the portal
folder_paths:
  root: /portal_files
  uploads: /portal_files/uploads
  import: /portal_files/import
  info_archive: /portal_files/info_archive
  output: /portal_files/output

# This file is used to configure the portal
folder_paths:
  root: /Users/ernie/Documents/GitHub/signalflow_portal/portal_files
  uploads: /Users/ernie/Documents/GitHub/signalflow_portal/portal_files/uploads
  import: /Users/ernie/Documents/GitHub/signalflow_portal/portal_files/import
  info_archive: /Users/ernie/Documents/GitHub/signalflow_portal/portal_files/info_archive
  output: /Users/ernie/Documents/GitHub/signalflow_portal/portal_files/output

# List of EEG formats
eeg_formats:
  - name: 'EGI128'
    description: 'Adult/Child 128 channel EGI Hydrocel net'
  - name: 'EGI32'
    description: 'Adult/Child 32 channel EGI Hydrocel net'
  - name: 'MEA30'
    description: 'NeuroNexus 30 channel MEA'
  - name: 'MEA30 (v2)'
    description: 'NeuroNexus Revision MEA'

# List of EEG paradigms
eeg_paradigms:
  - name: 'Resting'
    description: 'Subject is at rest with eyes open or closed'
  - name: 'Visual'
    description: 'Subject is presented with visual stimuli'
  - name: 'Auditory Chirp'
    description: 'Version B Click-Train 2023+'

eeg_analyses:
  - name: 'Mne-Connectivity-Default'
    category: 'Connectivity'
    description: 'All-to-all connectivity analysis'
    valid_formats: ['EGI128', 'EGI32', 'MEA30', 'MEA30 (v2)']
    valid_paradigms: ['Resting']
    parameters: None
  - name: 'Yasa-Bandpower-Default'
    category: 'Power'
    description: 'Bandpower analysis'
    valid_formats: ['EGI128', 'EGI32', 'MEA30', 'MEA30 (v2)']
    valid_paradigms: ['Resting']
    parameters: None